import {
  BadgeIndianRupee,
  Banknote,
  BarChart3,
  Bot,
  BriefcaseBusiness,
  Building2,
  Calculator,
  CalendarCheck,
  Car,
  ClipboardCheck,
  Cloud,
  Code2,
  CreditCard,
  FileCheck2,
  FileText,
  GraduationCap,
  Headphones,
  HeartPulse,
  Megaphone,
  MessageCircle,
  PackageCheck,
  PhoneCall,
  Rocket,
  Scale,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Stethoscope,
  Target,
  UserCheck,
  Users,
  type LucideIcon,
} from "lucide-react"

export type IndustrySolutionConfig = {
  badge: string
  title: string
  description: string
  businessName: string
  initials: string
  accent: string
  icon: LucideIcon
  stats: Array<{ value: string; label: string; note: string }>
  chatMessages: Array<{ from: "user" | "bot"; text: string }>
  servicesLabel: string
  servicesTitle: string
  servicesBody: string
  services: Array<{ icon: LucideIcon; title: string; body: string }>
  imageOne: { src: string; alt: string; width?: number; height?: number; unoptimized?: boolean }
  imageTwo: { src: string; alt: string }
  audiencesLabel: string
  audiencesTitle: string
  audiences: Array<{ icon: LucideIcon; title: string; text: string }>
  journeyLabel: string
  journeyTitle: string
  journey: Array<{ step: string; title: string; text: string }>
  dashboardTitle: string
  resultsTitle: string
  resultsBody: string
  comparison: Array<[string, string, string]>
  ctaTitle: string
  ctaBody: string
}

const SettingsIcon = Bot
const KeyIcon = Car

const defaultStats = [
  { value: "95%", label: "WhatsApp open rate", note: "Customers see updates fast" },
  { value: "3 sec", label: "First response", note: "Every inquiry gets attention" },
  { value: "24/7", label: "Lead coverage", note: "Works after business hours" },
  { value: "45%", label: "More conversions", note: "Automated follow-ups close gaps" },
]

const whatsappImage = { src: "/images/whatsapp-hero.png", alt: "WhatsApp automation conversation preview" }

export const solutionPages: Record<string, IndustrySolutionConfig> = {
  automobile: {
    badge: "WhatsApp automation for automobile service",
    title: "Convert every service inquiry into a confirmed workshop booking.",
    description:
      "DigitalBot answers service questions, shares estimates, captures vehicle details, books slots, and sends repair updates directly inside WhatsApp.",
    businessName: "SpeedX Auto Service",
    initials: "SX",
    accent: "Automobile",
    icon: Car,
    stats: defaultStats,
    chatMessages: [
      { from: "user", text: "Hi, I need to book a car service" },
      { from: "bot", text: "Welcome to SpeedX Auto Service. What service do you need?\n- Regular service\n- AC repair\n- Denting and painting\n- Insurance claim" },
      { from: "user", text: "Regular service for Honda City 2022" },
      { from: "bot", text: "Got it. The regular service package includes oil, filter, AC check, brake inspection, and a 40-point check. Estimated cost: Rs. 4,500. Want to book a slot?" },
      { from: "user", text: "Tomorrow morning" },
      { from: "bot", text: "Service booked for tomorrow at 9:00 AM. We can also arrange free pickup for your Honda City." },
    ],
    servicesLabel: "Designed for workshops",
    servicesTitle: "A complete WhatsApp service desk for automobile businesses.",
    servicesBody: "Built for garages, service centers, and auto brands that need quick booking, transparent updates, and repeat service reminders.",
    services: [
      { icon: CalendarCheck, title: "Service Booking", body: "Customers choose service packages, dates, pickup options, and workshop slots without phone calls." },
      { icon: ClipboardCheck, title: "Vehicle Qualification", body: "Collects model, year, mileage, service history, issue type, and photos before advisor handoff." },
      { icon: ShieldCheck, title: "Claim Assistance", body: "Guides customers through insurance claim documents, photos, and next steps in chat." },
      { icon: MessageCircle, title: "Live Service Updates", body: "Sends vehicle received, work started, approval needed, ready for pickup, and payment updates." },
      { icon: PackageCheck, title: "Parts Recommendations", body: "Suggests genuine parts, accessories, add-ons, and maintenance reminders based on the vehicle." },
      { icon: Bot, title: "Advisor Handoff", body: "Routes high-value or complex repairs to the right service advisor with full conversation history." },
    ],
    imageOne: { src: "/images/automobile_1.png", alt: "Automobile service team using automation" },
    imageTwo: { src: "/images/automobile_2.png", alt: "Automobile WhatsApp automation preview" },
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for garages, service centers, dealers, and accessory teams.",
    audiences: [
      { icon: Car, title: "Service Centers", text: "Bookings, estimates, pickup requests, repair approvals, and payment links." },
      { icon: SettingsIcon, title: "Repair Workshops", text: "Issue triage, photo collection, service status updates, and advisor handoffs." },
      { icon: PackageCheck, title: "Parts and Accessories", text: "Product inquiries, compatibility checks, quotations, and order updates." },
      { icon: Users, title: "Fleet Operators", text: "Maintenance reminders, bulk service bookings, vehicle records, and escalation alerts." },
    ],
    journeyLabel: "Customer journey",
    journeyTitle: "From service request to completed pickup.",
    journey: [
      { step: "01", title: "Customer asks on WhatsApp", text: "The AI understands the vehicle issue and answers basic service questions instantly." },
      { step: "02", title: "AI captures vehicle details", text: "Model, year, mileage, location, preferred slot, and photos are saved cleanly." },
      { step: "03", title: "Estimate and slot are shared", text: "Packages, expected cost, time needed, pickup option, and advisor details go out in chat." },
      { step: "04", title: "Service updates continue", text: "The customer receives approvals, payment links, and pickup notifications automatically." },
    ],
    dashboardTitle: "Automobile Service Dashboard",
    resultsTitle: "Real results for automobile service teams.",
    resultsBody: "See what changes when every booking, reminder, and status update runs through WhatsApp automation.",
    comparison: [
      ["Booking speed", "Instant service slot booking", "Missed calls and delayed callbacks"],
      ["Customer updates", "Live repair status in WhatsApp", "Customers keep calling the workshop"],
      ["Advisor workload", "Only qualified cases reach staff", "Advisors repeat the same details all day"],
      ["Follow-up", "Automated service reminders", "Customers forget maintenance dates"],
      ["Revenue", "Add-ons and parts suggested in chat", "Accessory upsell opportunities missed"],
    ],
    ctaTitle: "Ready to automate your service center?",
    ctaBody: "See a live WhatsApp service flow for your packages, vehicle types, pickup process, and advisor team.",
  },
  insurance: {
    badge: "WhatsApp automation for insurance",
    title: "Sell more policies and recover more renewals on WhatsApp.",
    description:
      "DigitalBot recommends plans, collects documents, books agent callbacks, answers policy questions, and sends renewal reminders automatically.",
    businessName: "SecureLife Insurance",
    initials: "SL",
    accent: "Insurance",
    icon: ShieldCheck,
    stats: [
      { value: "95%", label: "Open rate", note: "Renewal reminders are seen" },
      { value: "3 sec", label: "Quote response", note: "Prospects get quick guidance" },
      { value: "24/7", label: "Policy support", note: "Works beyond agent hours" },
      { value: "35%", label: "More renewals", note: "Smart reminders reduce lapses" },
    ],
    chatMessages: [
      { from: "user", text: "Hi, I need health insurance for my family" },
      { from: "bot", text: "Welcome to SecureLife. How many members should we cover?\n- Just me\n- Me and spouse\n- Family up to 4\n- Family 5+" },
      { from: "user", text: "Family of 4" },
      { from: "bot", text: "Great. What is the age of the eldest member and your preferred cover amount?" },
      { from: "user", text: "45 years, 10 lakh cover" },
      { from: "bot", text: "I recommend SecureFamily Plan. Premium: Rs. 18,500/year. Cover: Rs. 10 lakh. Cashless hospitals and annual health checkup included. Want an agent callback?" },
    ],
    servicesLabel: "Designed for policy teams",
    servicesTitle: "A WhatsApp desk for quotes, claims, documents, and renewals.",
    servicesBody: "Built for insurers, brokers, and agents who need faster lead qualification and reliable renewal follow-up.",
    services: [
      { icon: ShieldCheck, title: "Plan Recommendation", body: "Suggests policy options based on age, family size, cover amount, budget, and needs." },
      { icon: FileText, title: "Document Collection", body: "Collects KYC, medical details, nominee details, and forms directly inside WhatsApp." },
      { icon: CalendarCheck, title: "Agent Callback Booking", body: "Lets prospects choose callback slots and sends full context to the right agent." },
      { icon: CreditCard, title: "Renewal Reminders", body: "Sends premium reminders, payment links, grace-period nudges, and receipt updates." },
      { icon: FileCheck2, title: "Claim Status Updates", body: "Answers claim stage questions and sends document pending alerts automatically." },
      { icon: Bot, title: "Agent Handoff", body: "Escalates complex policy or claim cases with full chat history and next action." },
    ],
    imageOne: { src: "/images/insurance_1.png", alt: "Insurance " },
    imageTwo: { src: "/images/insurance_2.png", alt: "Insurance " },
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for insurers, brokers, agents, and renewal teams.",
    audiences: [
      { icon: ShieldCheck, title: "Insurance Companies", text: "Lead capture, plan education, claims support, and renewal reminders." },
      { icon: Users, title: "Broker Teams", text: "Comparison sharing, callback booking, document follow-up, and CRM updates." },
      { icon: PhoneCall, title: "Field Agents", text: "Qualified leads, customer context, appointment reminders, and renewal nudges." },
      { icon: FileCheck2, title: "Claims Teams", text: "Claim status, missing documents, escalation alerts, and customer updates." },
    ],
    journeyLabel: "Policy journey",
    journeyTitle: "From first inquiry to policy renewal.",
    journey: [
      { step: "01", title: "Prospect asks on WhatsApp", text: "The AI identifies policy type and answers core eligibility questions." },
      { step: "02", title: "AI captures profile details", text: "Age, family size, income, cover need, budget, and existing policy details are recorded." },
      { step: "03", title: "Plan options are shared", text: "Benefits, premium ranges, exclusions, documents, and callback options are sent in chat." },
      { step: "04", title: "Renewal is automated", text: "Payment reminders and renewal links go out before expiry so fewer policies lapse." },
    ],
    dashboardTitle: "Insurance Automation Dashboard",
    resultsTitle: "Real results for insurance sales and service teams.",
    resultsBody: "Every number improves when policy inquiries, reminders, and handoffs are handled instantly.",
    comparison: [
      ["Quote speed", "Instant plan guidance", "Slow calls and manual comparisons"],
      ["Document flow", "Collected inside WhatsApp", "Email chains and missing files"],
      ["Agent workload", "Qualified prospects reach agents", "Agents handle every repeated query"],
      ["Renewals", "Automated payment reminders", "Policies lapse from missed follow-up"],
      ["Claims", "Status updates in chat", "Customers keep calling for progress"],
    ],
    ctaTitle: "Ready to sell and renew more policies?",
    ctaBody: "See a live WhatsApp insurance flow for your policy types, documents, agents, claims, and renewals.",
  },
  healthcare: {
    badge: "WhatsApp automation for healthcare",
    title: "Turn patient inquiries into booked appointments faster.",
    description:
      "DigitalBot answers clinic questions, books appointments, sends reminders, collects patient details, and shares reports or payment links through WhatsApp.",
    businessName: "CarePlus Clinic",
    initials: "CP",
    accent: "Healthcare",
    icon: HeartPulse,
    stats: [
      { value: "95%", label: "Message open rate", note: "Patients see reminders fast" },
      { value: "3 sec", label: "First response", note: "No inquiry waits on hold" },
      { value: "24/7", label: "Patient support", note: "After-hours questions covered" },
      { value: "40%", label: "Fewer no-shows", note: "Automated visit reminders help" },
    ],
    chatMessages: [
      { from: "user", text: "Hi, I want to book a dermatologist appointment" },
      { from: "bot", text: "Welcome to CarePlus Clinic. I can help. Is this for today, tomorrow, or later this week?" },
      { from: "user", text: "Tomorrow evening" },
      { from: "bot", text: "Available slots tomorrow: 5:30 PM, 6:15 PM, and 7:00 PM. Please choose one." },
      { from: "user", text: "6:15 PM" },
      { from: "bot", text: "Appointment confirmed for tomorrow at 6:15 PM with Dr. Meera. Please share patient name and age." },
    ],
    servicesLabel: "Designed for care teams",
    servicesTitle: "A WhatsApp front desk for clinics, hospitals, and diagnostics.",
    servicesBody: "Built for healthcare teams that need appointment booking, patient reminders, and front-desk automation without losing the human touch.",
    services: [
      { icon: CalendarCheck, title: "Appointment Booking", body: "Books doctor visits, diagnostics, follow-ups, and teleconsultations directly in WhatsApp." },
      { icon: ClipboardCheck, title: "Patient Intake", body: "Collects name, age, symptoms, department, prior reports, and preferred time before the visit." },
      { icon: Stethoscope, title: "Department Routing", body: "Routes inquiries to the right doctor, specialty, lab, pharmacy, or care coordinator." },
      { icon: CreditCard, title: "Payment Links", body: "Shares consultation fees, package payments, receipts, and pending-payment reminders." },
      { icon: FileCheck2, title: "Report Updates", body: "Notifies patients when reports are ready and guides them to secure pickup or consultation." },
      { icon: Bot, title: "Staff Handoff", body: "Escalates urgent or complex cases to front-desk staff with patient context." },
    ],
    imageOne: { src: "/images/healthcare_1.png", alt: "Healthcare appointment automation" },
    imageTwo: { src: "/images/healthcare_2.png", alt: " appointment booking preview" },
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for clinics, hospitals, labs, and wellness centers.",
    audiences: [
      { icon: HeartPulse, title: "Clinics", text: "Appointment booking, reminders, intake forms, and follow-up visits." },
      { icon: Building2, title: "Hospitals", text: "Department routing, OPD booking, package inquiries, and patient updates." },
      { icon: FileCheck2, title: "Diagnostic Labs", text: "Test booking, home collection, report notifications, and payment links." },
      { icon: Users, title: "Wellness Centers", text: "Program inquiries, membership reminders, therapy slots, and care follow-ups." },
    ],
    journeyLabel: "Patient journey",
    journeyTitle: "From health inquiry to confirmed appointment.",
    journey: [
      { step: "01", title: "Patient messages the clinic", text: "The AI understands the specialty, concern, and preferred timing." },
      { step: "02", title: "Details are captured", text: "Patient profile, symptoms, reports, and urgency are recorded." },
      { step: "03", title: "Slot is confirmed", text: "Available doctors, fees, location, and preparation instructions are shared." },
      { step: "04", title: "Follow-up continues", text: "Reminders, payment links, reports, and revisit prompts are sent automatically." },
    ],
    dashboardTitle: "Healthcare Appointment Dashboard",
    resultsTitle: "Real results for healthcare front desks.",
    resultsBody: "Patients get answers quickly while staff spend less time on repetitive calls.",
    comparison: [
      ["Booking speed", "Instant appointment slots", "Phone queues and missed calls"],
      ["Patient details", "Captured before visit", "Collected manually at reception"],
      ["No-shows", "Automated reminders", "Patients forget timings"],
      ["Staff workload", "Routine FAQs automated", "Front desk repeats the same answers"],
      ["Follow-up", "Reports and revisit reminders", "Manual calls after every visit"],
    ],
    ctaTitle: "Ready to automate patient appointments?",
    ctaBody: "See a live WhatsApp healthcare flow for your doctors, departments, diagnostics, and follow-up process.",
  },
  saas: {
    badge: "WhatsApp automation for SaaS",
    title: "Convert trials, demos, and support chats into paying customers.",
    description:
      "DigitalBot qualifies SaaS leads, books product demos, answers pricing questions, nudges trials, and routes support issues to your team.",
    businessName: "CloudStack SaaS",
    initials: "CS",
    accent: "SaaS",
    icon: Cloud,
    stats: defaultStats,
    chatMessages: [
      { from: "user", text: "Hi, I want to know your CRM pricing" },
      { from: "bot", text: "Welcome to CloudStack. How many users do you need?\n- 1 to 5\n- 6 to 25\n- 26 to 100\n- 100+" },
      { from: "user", text: "Around 20 users" },
      { from: "bot", text: "For 20 users, our Growth plan is a good fit. It includes pipelines, automation, reports, and WhatsApp integrations. Want to book a demo?" },
      { from: "user", text: "Yes, tomorrow" },
      { from: "bot", text: "Demo booked for tomorrow at 3:00 PM. I have shared the invite and product checklist." },
    ],
    servicesLabel: "Designed for SaaS growth",
    servicesTitle: "A WhatsApp sales and support assistant for software teams.",
    servicesBody: "Built for SaaS companies that need fast demo booking, trial activation, onboarding reminders, and support triage.",
    services: [
      { icon: Target, title: "Lead Qualification", body: "Captures use case, team size, budget, timeline, tech stack, and decision-maker details." },
      { icon: CalendarCheck, title: "Demo Booking", body: "Lets prospects choose demo slots and sends pre-demo questions automatically." },
      { icon: CreditCard, title: "Pricing Guidance", body: "Explains plans, billing cycles, add-ons, and upgrades in simple WhatsApp flows." },
      { icon: Rocket, title: "Trial Activation", body: "Nudges users to complete setup, invite teammates, and reach activation milestones." },
      { icon: Headphones, title: "Support Triage", body: "Collects issue details, screenshots, plan type, and urgency before handoff." },
      { icon: Bot, title: "Sales Handoff", body: "Routes qualified accounts to sales with full chat context and next-best action." },
    ],
    imageOne: { src: "/images/SaaS_1.png", alt: "SaaS team managing customer automation" },
    imageTwo: { src: "/images/SaaS_2.png", alt: "SaaS team managing customer automation" },
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for SaaS sales, onboarding, support, and success.",
    audiences: [
      { icon: Rocket, title: "Startup SaaS", text: "Trial inquiries, onboarding nudges, pricing answers, and founder-led sales support." },
      { icon: Users, title: "Sales Teams", text: "Lead qualification, demo booking, deal routing, and follow-up automation." },
      { icon: Headphones, title: "Support Teams", text: "Ticket triage, status updates, help article sharing, and escalation." },
      { icon: BarChart3, title: "Customer Success", text: "Renewal reminders, adoption nudges, expansion signals, and account updates." },
    ],
    journeyLabel: "SaaS journey",
    journeyTitle: "From product interest to activated account.",
    journey: [
      { step: "01", title: "Prospect asks on WhatsApp", text: "The AI understands product interest, pain point, and buying intent." },
      { step: "02", title: "Lead is qualified", text: "Company size, stack, budget, timeline, and user count are recorded." },
      { step: "03", title: "Demo or trial is booked", text: "The right plan, demo slot, trial link, and setup checklist are shared." },
      { step: "04", title: "Activation is nudged", text: "Users receive onboarding prompts and your team sees hot accounts." },
    ],
    dashboardTitle: "SaaS Growth Dashboard",
    resultsTitle: "Real results for SaaS revenue teams.",
    resultsBody: "More demos get booked and more trials become active when follow-up happens instantly.",
    comparison: [
      ["Demo booking", "Instant calendar slots", "Back-and-forth emails"],
      ["Trial activation", "Automated setup nudges", "Users sign up and go silent"],
      ["Support triage", "Issue details captured first", "Agents ask basic questions repeatedly"],
      ["Sales focus", "Qualified accounts reach reps", "Reps chase low-fit leads"],
      ["Renewals", "Usage and billing reminders", "Renewal risk spotted late"],
    ],
    ctaTitle: "Ready to convert more SaaS leads?",
    ctaBody: "See a live WhatsApp SaaS flow for your pricing, demos, onboarding, integrations, and support process.",
  },
  ecommerce: {
    badge: "WhatsApp automation for e-commerce",
    title: "Recover carts, answer product questions, and grow repeat orders.",
    description:
      "DigitalBot helps shoppers find products, answers delivery questions, recovers abandoned carts, sends order updates, and handles returns on WhatsApp.",
    businessName: "UrbanCart Store",
    initials: "UC",
    accent: "E-commerce",
    icon: ShoppingBag,
    stats: [
      { value: "95%", label: "Message open rate", note: "Offers and updates get seen" },
      { value: "3 sec", label: "Product response", note: "Shoppers get instant help" },
      { value: "24/7", label: "Store support", note: "Always-on buying assistance" },
      { value: "32%", label: "Cart recovery", note: "Automated nudges bring orders back" },
    ],
    chatMessages: [
      { from: "user", text: "Do you have black running shoes in size 8?" },
      { from: "bot", text: "Yes, we have 3 options in size 8. Would you like budget, premium, or best-selling options?" },
      { from: "user", text: "Best-selling" },
      { from: "bot", text: "Our FlexRun Pro is the top seller. Price: Rs. 2,499. Delivery in 2-3 days. Want checkout link?" },
      { from: "user", text: "Yes" },
      { from: "bot", text: "Here is your checkout link. I will also send order tracking once payment is complete." },
    ],
    servicesLabel: "Designed for online stores",
    servicesTitle: "A WhatsApp sales assistant for discovery, checkout, and support.",
    servicesBody: "Built for D2C brands and retailers who need faster product answers, cart recovery, and repeat purchase campaigns.",
    services: [
      { icon: ShoppingBag, title: "Product Finder", body: "Recommends products by size, budget, color, use case, and availability." },
      { icon: CreditCard, title: "Cart Recovery", body: "Sends personalized checkout reminders with offers, links, and urgency triggers." },
      { icon: PackageCheck, title: "Order Updates", body: "Shares payment, packing, shipping, delivery, and return status automatically." },
      { icon: MessageCircle, title: "Customer Support", body: "Answers delivery, exchange, return, cancellation, and warranty questions." },
      { icon: Megaphone, title: "Campaign Broadcasts", body: "Runs launch, sale, restock, and repeat-purchase campaigns on WhatsApp." },
      { icon: Bot, title: "Agent Handoff", body: "Escalates high-value shoppers or complex return cases with full context." },
    ],
    imageOne: { src: "/images/e_commerce_1.png", alt: "E-commerce customer automation" },
    imageTwo: { src: "/images/e_commerce_2.png", alt: "E-commerce customer automation" },
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for D2C, retail, marketplace, and support teams.",
    audiences: [
      { icon: ShoppingBag, title: "D2C Brands", text: "Product discovery, cart recovery, COD confirmation, and repeat sales." },
      { icon: PackageCheck, title: "Retail Stores", text: "Stock inquiries, store pickup, order updates, and customer service." },
      { icon: Megaphone, title: "Campaign Teams", text: "Launch alerts, sale reminders, restock nudges, and segmented offers." },
      { icon: Headphones, title: "Support Teams", text: "Returns, exchanges, refunds, delivery questions, and escalation." },
    ],
    journeyLabel: "Shopper journey",
    journeyTitle: "From product question to repeat purchase.",
    journey: [
      { step: "01", title: "Shopper asks on WhatsApp", text: "The AI understands product need, size, color, budget, and urgency." },
      { step: "02", title: "Products are recommended", text: "Relevant options, availability, images, prices, and delivery estimates are shared." },
      { step: "03", title: "Checkout is nudged", text: "Payment links, cart recovery messages, and COD confirmations move the order forward." },
      { step: "04", title: "Support continues", text: "Tracking, returns, exchanges, and repeat offers stay inside WhatsApp." },
    ],
    dashboardTitle: "E-commerce Revenue Dashboard",
    resultsTitle: "Real results for e-commerce teams.",
    resultsBody: "More shoppers complete orders when answers, reminders, and tracking happen where they already chat.",
    comparison: [
      ["Product discovery", "Instant recommendations", "Customers search and leave"],
      ["Cart recovery", "Personalized WhatsApp nudges", "Abandoned carts stay abandoned"],
      ["Order updates", "Automated tracking messages", "Support tickets for simple status"],
      ["Repeat sales", "Segmented offers in chat", "One-off purchases only"],
      ["Support", "Returns handled in WhatsApp", "Email threads and slow replies"],
    ],
    ctaTitle: "Ready to recover more e-commerce revenue?",
    ctaBody: "See a live WhatsApp commerce flow for your catalog, checkout, shipping, returns, and campaigns.",
  },
  bpo: {
    badge: "WhatsApp automation for BPO",
    title: "Handle more customer conversations without increasing call pressure.",
    description:
      "DigitalBot automates FAQs, ticket intake, appointment callbacks, escalation routing, and status updates for BPO and contact-center teams.",
    businessName: "ConnectHub BPO",
    initials: "CH",
    accent: "BPO",
    icon: Headphones,
    stats: [
      { value: "70%", label: "FAQ deflection", note: "Routine queries automated" },
      { value: "3 sec", label: "First response", note: "No customer waits in queue" },
      { value: "24/7", label: "Coverage", note: "Night and weekend support" },
      { value: "45%", label: "Lower call load", note: "Agents focus on escalations" },
    ],
    chatMessages: [
      { from: "user", text: "I need help with my service request" },
      { from: "bot", text: "I can help. Please choose an option:\n- Track ticket\n- Raise complaint\n- Request callback\n- Talk to agent" },
      { from: "user", text: "Track ticket" },
      { from: "bot", text: "Please share your ticket ID or registered phone number." },
      { from: "user", text: "SR20481" },
      { from: "bot", text: "Your ticket is in progress and assigned to Level 2 support. Expected resolution: today by 6 PM." },
    ],
    servicesLabel: "Designed for contact centers",
    servicesTitle: "A WhatsApp support layer for BPO operations.",
    servicesBody: "Built for support teams that need faster intake, better routing, fewer repetitive calls, and clear escalation context.",
    services: [
      { icon: MessageCircle, title: "FAQ Automation", body: "Answers repetitive policy, service, billing, and status questions around the clock." },
      { icon: ClipboardCheck, title: "Ticket Intake", body: "Collects issue category, customer ID, screenshots, urgency, and callback preference." },
      { icon: PhoneCall, title: "Callback Scheduling", body: "Lets customers choose callback slots and reduces inbound queue pressure." },
      { icon: Headphones, title: "Agent Routing", body: "Sends the right cases to the right queue with full customer context." },
      { icon: BarChart3, title: "SLA Visibility", body: "Tracks pending cases, escalations, response time, and resolution progress." },
      { icon: Bot, title: "Human Handoff", body: "Escalates complex or unhappy customers cleanly to live agents." },
    ],
    imageOne: { src: "/images/bpo_2.png", alt: "BPO customer support automation" },
    imageTwo: { src: "/images/bpo_1.png", alt: "SaaS team managing customer automation" },
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for inbound, outbound, back-office, and escalation teams.",
    audiences: [
      { icon: Headphones, title: "Inbound Support", text: "FAQ deflection, ticket intake, callback booking, and status checks." },
      { icon: PhoneCall, title: "Outbound Teams", text: "Follow-ups, reminders, survey flows, and customer reactivation." },
      { icon: ClipboardCheck, title: "Back Office", text: "Document collection, verification tasks, and process updates." },
      { icon: Users, title: "Escalation Desks", text: "Priority routing, complaint context, SLA alerts, and supervisor updates." },
    ],
    journeyLabel: "Support journey",
    journeyTitle: "From customer question to resolved ticket.",
    journey: [
      { step: "01", title: "Customer starts a chat", text: "The AI understands the request and shows the right support options." },
      { step: "02", title: "Issue details are captured", text: "Ticket ID, customer details, category, screenshots, and urgency are recorded." },
      { step: "03", title: "Answer or ticket is shared", text: "Simple queries are resolved instantly; complex cases get routed to agents." },
      { step: "04", title: "Status updates continue", text: "Customers get resolution progress, callback reminders, and closure messages." },
    ],
    dashboardTitle: "BPO Support Dashboard",
    resultsTitle: "Real results for BPO and contact-center teams.",
    resultsBody: "Lower queue load and faster response times come from handling routine conversations before they become calls.",
    comparison: [
      ["Queue pressure", "Routine queries automated", "Every question becomes a call"],
      ["Ticket intake", "Structured details captured", "Agents chase missing information"],
      ["Callback flow", "Slots booked in WhatsApp", "Missed calls and repeat dialing"],
      ["Escalation", "Context-rich handoff", "Customers repeat their story"],
      ["SLA updates", "Automated status messages", "Customers call for progress"],
    ],
    ctaTitle: "Ready to reduce support pressure?",
    ctaBody: "See a live WhatsApp BPO flow for your queues, scripts, SLAs, teams, and escalation paths.",
  },
  "car-dealership": {
    badge: "WhatsApp automation for car dealerships",
    title: "Turn vehicle inquiries into showroom visits, test drives, and bookings.",
    description:
      "DigitalBot answers model questions, checks budget, books test drives, shares offers, and routes hot buyers to sales consultants.",
    businessName: "PrimeDrive Motors",
    initials: "PD",
    accent: "Car Dealership",
    icon: Car,
    stats: [
      { value: "95%", label: "Open rate", note: "Offers and test-drive reminders seen" },
      { value: "3 sec", label: "First response", note: "Every buyer gets instant attention" },
      { value: "24/7", label: "Lead coverage", note: "Weekend and after-hours leads captured" },
      { value: "42%", label: "More visits", note: "Automated reminders improve turnout" },
    ],
    chatMessages: [
      { from: "user", text: "Hi, I want to know about the new SUV" },
      { from: "bot", text: "Welcome to PrimeDrive Motors. Are you interested in price, variants, test drive, exchange, or finance?" },
      { from: "user", text: "Test drive and finance" },
      { from: "bot", text: "Sure. Please share your preferred location, budget, and current car if you want exchange." },
      { from: "user", text: "Baner showroom, budget 15 lakh" },
      { from: "bot", text: "Test drive booked at Baner showroom for Saturday 11 AM. I have also shared EMI options for your budget." },
    ],
    servicesLabel: "Designed for dealerships",
    servicesTitle: "A WhatsApp sales desk for showroom teams.",
    servicesBody: "Built for new-car, used-car, and multi-brand dealerships that need faster responses and better test-drive conversion.",
    services: [
      { icon: Car, title: "Model Inquiry Bot", body: "Answers variant, color, mileage, delivery, price, and feature questions instantly." },
      { icon: CalendarCheck, title: "Test Drive Booking", body: "Books showroom or doorstep test drives and sends reminders to reduce no-shows." },
      { icon: BadgeIndianRupee, title: "Finance Guidance", body: "Shares EMI ranges, down-payment options, exchange estimates, and offer details." },
      { icon: ClipboardCheck, title: "Lead Qualification", body: "Captures budget, model interest, location, purchase timeline, and exchange details." },
      { icon: Megaphone, title: "Offer Campaigns", body: "Runs festive offers, launch alerts, exchange bonuses, and booking nudges." },
      { icon: Bot, title: "Sales Handoff", body: "Routes hot buyers to sales consultants with full context and next step." },
    ],
    imageOne: { src: "/images/car_dealership_1.png", alt: "Car dealership sales consultant automation" },
    imageTwo: { src: "/images/car_dealership_2.png", alt: "Car dealership sales consultant automation" },
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for new cars, used cars, finance, and showroom teams.",
    audiences: [
      { icon: Car, title: "New Car Dealers", text: "Model inquiries, offers, test drives, booking updates, and delivery alerts." },
      { icon: KeyIcon, title: "Used Car Teams", text: "Inventory matching, inspection booking, valuation, and resale follow-up." },
      { icon: Banknote, title: "Finance Teams", text: "EMI guidance, loan documents, approval updates, and payment reminders." },
      { icon: Users, title: "Sales Consultants", text: "Qualified buyers, chat context, visit reminders, and CRM-ready leads." },
    ],
    journeyLabel: "Buyer journey",
    journeyTitle: "From vehicle interest to showroom visit.",
    journey: [
      { step: "01", title: "Buyer asks on WhatsApp", text: "The AI identifies model, budget, variant, and purchase intent." },
      { step: "02", title: "Preferences are captured", text: "Location, finance need, exchange vehicle, color, and timeline are recorded." },
      { step: "03", title: "Offer and slot are shared", text: "Brochure, EMI, showroom route, and test-drive slot are sent instantly." },
      { step: "04", title: "Consultant follows up", text: "The sales team receives a qualified lead with complete conversation context." },
    ],
    dashboardTitle: "Car Dealership Dashboard",
    resultsTitle: "Real results for dealership sales teams.",
    resultsBody: "Showroom teams convert more inquiries when every buyer gets instant answers and timely test-drive reminders.",
    comparison: [
      ["Response speed", "Instant buyer replies", "Slow callbacks after ad leads"],
      ["Test drives", "Automated slot booking", "Manual scheduling and no-shows"],
      ["Finance", "EMI shared inside chat", "Customers wait for loan calls"],
      ["Sales workload", "Hot leads reach consultants", "Consultants chase casual inquiries"],
      ["Campaigns", "Offers sent on WhatsApp", "Broadcasts lack context"],
    ],
    ctaTitle: "Ready to book more test drives?",
    ctaBody: "See a live WhatsApp dealership flow for your models, offers, locations, finance, and sales team.",
  },
  coaching: {
    badge: "WhatsApp automation for coaching institutes",
    title: "Convert course inquiries into demo classes and paid enrollments.",
    description:
      "DigitalBot answers course questions, shares batch details, qualifies students, books demo classes, and sends fee reminders on WhatsApp.",
    businessName: "RankPro Coaching",
    initials: "RP",
    accent: "Coaching",
    icon: GraduationCap,
    stats: [
      { value: "95%", label: "Open rate", note: "Students see batch updates" },
      { value: "3 sec", label: "First response", note: "No inquiry waits for counselor" },
      { value: "24/7", label: "Student support", note: "After-hours inquiries captured" },
      { value: "55%", label: "More demos", note: "Automated follow-ups improve booking" },
    ],
    chatMessages: [
      { from: "user", text: "Hi, do you have NEET crash course?" },
      { from: "bot", text: "Yes. Our NEET crash course has weekday and weekend batches. Which class are you in?" },
      { from: "user", text: "Class 12" },
      { from: "bot", text: "Great. The next Class 12 batch starts Monday. Fee: Rs. 18,000. Want a free demo class?" },
      { from: "user", text: "Yes, Sunday" },
      { from: "bot", text: "Demo class booked for Sunday at 10 AM. I have shared syllabus, faculty details, and location." },
    ],
    servicesLabel: "Designed for admissions",
    servicesTitle: "A WhatsApp admission desk for coaching and training teams.",
    servicesBody: "Built for institutes that need course counseling, demo booking, batch updates, and fee follow-up without manual chasing.",
    services: [
      { icon: MessageCircle, title: "Course Inquiry Bot", body: "Answers course, exam, faculty, fee, batch, result, and location questions instantly." },
      { icon: ClipboardCheck, title: "Student Qualification", body: "Captures class, exam target, location, budget, current preparation level, and parent details." },
      { icon: CalendarCheck, title: "Demo Class Booking", body: "Lets students choose demo slots and sends reminders to student and parent." },
      { icon: CreditCard, title: "Fee Reminders", body: "Sends installment alerts, payment links, receipt updates, and scholarship reminders." },
      { icon: Megaphone, title: "Batch Campaigns", body: "Promotes new batches, crash courses, webinars, and exam-alert campaigns." },
      { icon: Bot, title: "Counselor Handoff", body: "Routes hot leads to the right counselor with student context." },
    ],
    imageOne: { src: "/images/coaching_1.png", alt: "Coaching student automation", width: 1600, height: 800, unoptimized: true },
    imageTwo: { src: "/images/coaching_2.png", alt: "Coaching WhatsApp admission form" },
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for test prep, skill training, tutors, and online academies.",
    audiences: [
      { icon: GraduationCap, title: "Test Prep Institutes", text: "Course inquiries, demo classes, exam FAQs, and batch updates." },
      { icon: Users, title: "Tuition Centers", text: "Parent inquiries, timetable updates, fee reminders, and PTM alerts." },
      { icon: Rocket, title: "Skill Academies", text: "Program counseling, webinars, trial classes, and certification updates." },
      { icon: Cloud, title: "Online Coaches", text: "Trial sessions, subscriptions, community updates, and learner support." },
    ],
    journeyLabel: "Student journey",
    journeyTitle: "From course question to paid enrollment.",
    journey: [
      { step: "01", title: "Student asks on WhatsApp", text: "The AI understands the exam, course, or batch interest." },
      { step: "02", title: "Student details are captured", text: "Class, target exam, location, timing, parent contact, and urgency are recorded." },
      { step: "03", title: "Demo gets booked", text: "Batch details, syllabus, fees, faculty, and demo slot are shared." },
      { step: "04", title: "Enrollment follow-up runs", text: "Fee reminders, counselor calls, and batch-start nudges continue automatically." },
    ],
    dashboardTitle: "Coaching Admission Dashboard",
    resultsTitle: "Real results for coaching institutes.",
    resultsBody: "More demos become admissions when every student and parent gets timely WhatsApp follow-up.",
    comparison: [
      ["Course answers", "Instant WhatsApp replies", "Counselors repeat FAQs"],
      ["Demo booking", "Slots confirmed in chat", "Manual calls and missed demos"],
      ["Parent follow-up", "Automated reminders", "Spreadsheets and late calls"],
      ["Fee collection", "Payment links and nudges", "Installments missed"],
      ["Counselor focus", "Only qualified leads reach staff", "Every casual inquiry consumes time"],
    ],
    ctaTitle: "Ready to fill more demo classes?",
    ctaBody: "See a live WhatsApp coaching flow for your courses, batches, fees, counselors, and student follow-up.",
  },
  marketing: {
    badge: "WhatsApp automation for marketing agencies",
    title: "Capture campaign leads and follow up before competitors do.",
    description:
      "DigitalBot qualifies inbound leads, shares portfolios, books strategy calls, runs campaign updates, and reports lead activity on WhatsApp.",
    businessName: "GrowthLane Agency",
    initials: "GL",
    accent: "Marketing",
    icon: Megaphone,
    stats: defaultStats,
    chatMessages: [
      { from: "user", text: "Hi, I need digital marketing for my clinic" },
      { from: "bot", text: "Welcome to GrowthLane. Which service do you need?\n- Lead generation\n- Social media\n- SEO\n- WhatsApp campaigns" },
      { from: "user", text: "Lead generation" },
      { from: "bot", text: "Great. What monthly budget and target city should we plan for?" },
      { from: "user", text: "Rs. 80,000, Pune" },
      { from: "bot", text: "Perfect. I have shared relevant case studies and booked a strategy call tomorrow at 12 PM." },
    ],
    servicesLabel: "Designed for agencies",
    servicesTitle: "A WhatsApp lead desk for marketing and campaign teams.",
    servicesBody: "Built for agencies that need faster qualification, better proposal follow-up, and campaign communication that clients actually read.",
    services: [
      { icon: Target, title: "Lead Qualification", body: "Captures industry, goals, budget, location, current channels, and decision timeline." },
      { icon: CalendarCheck, title: "Strategy Call Booking", body: "Books discovery calls and sends briefs, case studies, and reminders automatically." },
      { icon: FileText, title: "Proposal Follow-Up", body: "Nudges prospects after proposal sharing and answers common package questions." },
      { icon: Megaphone, title: "Campaign Broadcasts", body: "Runs segmented offers, launch alerts, and reactivation campaigns for clients." },
      { icon: BarChart3, title: "Performance Updates", body: "Sends lead counts, campaign summaries, and weekly progress updates in WhatsApp." },
      { icon: Bot, title: "Team Handoff", body: "Routes hot leads to sales or account managers with complete context." },
    ],
    imageOne: { src: "/images/marketing_1.png", alt: "Marketing campaign automation" },
    imageTwo: { src: "/images/marketing_2.png", alt: "Lead generation automation preview" },
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for agencies, performance teams, social teams, and client success.",
    audiences: [
      { icon: Megaphone, title: "Marketing Agencies", text: "Inbound qualification, case-study sharing, call booking, and proposal follow-up." },
      { icon: Target, title: "Performance Teams", text: "Lead routing, campaign alerts, CPL summaries, and client reporting." },
      { icon: Users, title: "Social Media Teams", text: "Content approvals, campaign reminders, inquiry capture, and audience updates." },
      { icon: BarChart3, title: "Client Success", text: "Weekly reports, escalation alerts, review requests, and renewal nudges." },
    ],
    journeyLabel: "Campaign journey",
    journeyTitle: "From inbound lead to strategy call.",
    journey: [
      { step: "01", title: "Prospect responds to a campaign", text: "The AI understands their business type and marketing goal." },
      { step: "02", title: "Lead details are captured", text: "Budget, location, services needed, current channels, and timeline are recorded." },
      { step: "03", title: "Proof and offer are shared", text: "Case studies, package options, call slots, and next steps are sent in chat." },
      { step: "04", title: "Follow-up continues", text: "Proposal nudges, reminders, and sales handoffs happen automatically." },
    ],
    dashboardTitle: "Marketing Agency Dashboard",
    resultsTitle: "Real results for marketing teams.",
    resultsBody: "Campaign ROI improves when leads are qualified and followed up instantly in the same channel.",
    comparison: [
      ["Lead capture", "Instant WhatsApp qualification", "Form leads go cold"],
      ["Call booking", "Slots booked automatically", "Manual coordination delays calls"],
      ["Proposal follow-up", "Automated reminders", "Sales team forgets warm prospects"],
      ["Client updates", "Reports sent in chat", "Clients ask for progress repeatedly"],
      ["Campaign speed", "Fast routing and handoff", "Leads sit in sheets"],
    ],
    ctaTitle: "Ready to convert more campaign leads?",
    ctaBody: "See a live WhatsApp marketing flow for your services, packages, campaigns, reporting, and sales handoff.",
  },
  consulting: {
    badge: "WhatsApp automation for consulting",
    title: "Qualify prospects and book advisory calls without manual follow-up.",
    description:
      "DigitalBot captures business needs, shares service packages, books consultations, collects documents, and routes clients to the right consultant.",
    businessName: "NorthStar Consulting",
    initials: "NS",
    accent: "Consulting",
    icon: BriefcaseBusiness,
    stats: defaultStats,
    chatMessages: [
      { from: "user", text: "Hi, I need help improving my sales process" },
      { from: "bot", text: "Welcome to NorthStar Consulting. What is your company size and current monthly revenue range?" },
      { from: "user", text: "25 people, around Rs. 40 lakh monthly" },
      { from: "bot", text: "Thanks. Do you need strategy, sales systems, hiring, or automation support?" },
      { from: "user", text: "Sales systems" },
      { from: "bot", text: "I have shared our sales audit overview and booked a consultation tomorrow at 4 PM." },
    ],
    servicesLabel: "Designed for advisors",
    servicesTitle: "A WhatsApp intake desk for consulting firms.",
    servicesBody: "Built for consultants who need structured discovery, faster call booking, and professional follow-up before the first meeting.",
    services: [
      { icon: ClipboardCheck, title: "Discovery Intake", body: "Captures company size, goals, pain points, budget, timeline, and decision makers." },
      { icon: CalendarCheck, title: "Consultation Booking", body: "Books advisory calls and sends preparation questions automatically." },
      { icon: FileText, title: "Document Collection", body: "Collects briefs, reports, screenshots, financials, or process notes before the call." },
      { icon: BriefcaseBusiness, title: "Service Matching", body: "Suggests audit, strategy, implementation, or retainer paths based on client needs." },
      { icon: BarChart3, title: "Pipeline Updates", body: "Tracks qualified leads, call outcomes, proposals, and follow-up stages." },
      { icon: Bot, title: "Consultant Handoff", body: "Routes prospects to the right consultant with context and next action." },
    ],
    imageOne: { src: "/images/consulting_1.png", alt: "Consulting client intake automation" },
    imageTwo:{ src: "/images/consulting_2.png", alt: "Consulting client intake automation" } ,
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for strategy, operations, growth, and advisory teams.",
    audiences: [
      { icon: BriefcaseBusiness, title: "Strategy Consultants", text: "Lead intake, discovery questions, call booking, and proposal follow-up." },
      { icon: BarChart3, title: "Growth Advisors", text: "Audit requests, funnel reviews, KPI collection, and implementation nudges." },
      { icon: Users, title: "HR Consultants", text: "Hiring needs, policy questions, assessment calls, and client updates." },
      { icon: Scale, title: "Business Advisors", text: "Compliance reminders, financial intake, advisory calls, and retainer updates." },
    ],
    journeyLabel: "Client journey",
    journeyTitle: "From first inquiry to qualified consultation.",
    journey: [
      { step: "01", title: "Prospect asks for help", text: "The AI understands the business problem and urgency." },
      { step: "02", title: "Discovery data is captured", text: "Goals, size, budget, timeline, stakeholders, and constraints are recorded." },
      { step: "03", title: "Consultation is booked", text: "The right service path, call slot, and prep checklist are shared." },
      { step: "04", title: "Proposal follow-up runs", text: "Reminders and next steps continue until the engagement moves forward." },
    ],
    dashboardTitle: "Consulting Pipeline Dashboard",
    resultsTitle: "Real results for consulting teams.",
    resultsBody: "Consultants spend more time advising when intake and follow-up are handled automatically.",
    comparison: [
      ["Discovery", "Structured intake in WhatsApp", "Unclear calls with missing context"],
      ["Call booking", "Calendar slots confirmed", "Manual scheduling delays"],
      ["Document collection", "Files requested upfront", "Consultants chase documents later"],
      ["Proposal follow-up", "Automated nudges", "Warm leads go quiet"],
      ["Team routing", "Right consultant assigned", "Every lead lands in one inbox"],
    ],
    ctaTitle: "Ready to book better consulting calls?",
    ctaBody: "See a live WhatsApp consulting flow for your services, discovery process, proposals, and advisor team.",
  },
  "accounting-legal": {
    badge: "WhatsApp automation for accounting",
    title: "Collect documents, answer compliance questions, and close client follow-ups faster.",
    description:
      "DigitalBot reminds clients about filings, collects documents, shares payment links, books consultations, and keeps accounting work moving.",
    businessName: "LedgerWise Accounting",
    initials: "LW",
    accent: "Accounting",
    icon: Calculator,
    stats: [
      { value: "95%", label: "Open rate", note: "Clients see filing reminders" },
      { value: "3 sec", label: "First response", note: "Routine queries answered fast" },
      { value: "24/7", label: "Client support", note: "After-hours intake covered" },
      { value: "50%", label: "Faster documents", note: "Automated reminders reduce chasing" },
    ],
    chatMessages: [
      { from: "user", text: "Hi, what documents are needed for GST filing?" },
      { from: "bot", text: "For GST filing, please share sales invoices, purchase invoices, expense bills, bank statement, and previous return details." },
      { from: "user", text: "Can I upload them here?" },
      { from: "bot", text: "Yes. Upload photos, PDFs, or Excel files here. I will tag them to your account." },
      { from: "user", text: "Also book a call" },
      { from: "bot", text: "Call booked tomorrow at 11 AM with your accountant. I have sent the document checklist too." },
    ],
    servicesLabel: "Designed for accounting teams",
    servicesTitle: "A WhatsApp client desk for filings, documents, and reminders.",
    servicesBody: "Built for accounting firms that need less document chasing, cleaner intake, and timely client communication.",
    services: [
      { icon: FileText, title: "Document Collection", body: "Collects invoices, bank statements, receipts, payroll data, and tax documents in chat." },
      { icon: CalendarCheck, title: "Filing Reminders", body: "Sends GST, TDS, income tax, payroll, and compliance deadline reminders." },
      { icon: Calculator, title: "Accounting FAQs", body: "Answers common filing, due date, invoice, deduction, and payment questions." },
      { icon: CreditCard, title: "Fee Collection", body: "Shares service invoices, payment links, receipts, and overdue-payment nudges." },
      { icon: Scale, title: "Compliance Updates", body: "Notifies clients about rule changes, pending tasks, and required approvals." },
      { icon: Bot, title: "Accountant Handoff", body: "Routes complex questions to accountants with client history and files." },
    ],
    imageOne: { src: "/images/accounting_1.png", alt: "Accounting client document automation" },
    imageTwo: { src: "/images/accounting_2.png", alt: "Accounting client document automation" },
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for accountants, bookkeepers, tax teams, and compliance advisors.",
    audiences: [
      { icon: Calculator, title: "Accounting Firms", text: "Document collection, client reminders, payment follow-up, and task updates." },
      { icon: FileCheck2, title: "Tax Consultants", text: "Return intake, due date reminders, filing status, and refund updates." },
      { icon: Banknote, title: "Bookkeeping Teams", text: "Monthly statements, expense collection, reconciliation notes, and reports." },
      { icon: Scale, title: "Compliance Advisors", text: "Regulatory reminders, approval workflows, and client notifications." },
    ],
    journeyLabel: "Client journey",
    journeyTitle: "From document request to completed filing.",
    journey: [
      { step: "01", title: "Client asks on WhatsApp", text: "The AI answers filing, document, due-date, and fee questions instantly." },
      { step: "02", title: "Documents are requested", text: "A checklist is shared based on service type and missing files are tracked." },
      { step: "03", title: "Review gets scheduled", text: "Accountant calls, approvals, and payment links are coordinated in chat." },
      { step: "04", title: "Filing updates are sent", text: "Submission status, receipts, and future reminders go out automatically." },
    ],
    dashboardTitle: "Accounting Client Dashboard",
    resultsTitle: "Real results for accounting firms.",
    resultsBody: "Filing work moves faster when document collection and reminders happen on WhatsApp.",
    comparison: [
      ["Document collection", "Checklist and uploads in WhatsApp", "Files scattered across email"],
      ["Deadlines", "Automated filing reminders", "Clients remember too late"],
      ["Client support", "Routine questions automated", "Accountants answer the same FAQs"],
      ["Payments", "Links and reminders sent", "Fees chased manually"],
      ["Status", "Filing progress updates", "Clients keep calling for updates"],
    ],
    ctaTitle: "Ready to reduce client chasing?",
    ctaBody: "See a live WhatsApp accounting flow for your filings, document lists, reminders, invoices, and client process.",
  },
  "financial-services": {
    badge: "WhatsApp automation for financial services",
    title: "Qualify finance leads and guide customers from inquiry to application.",
    description:
      "DigitalBot captures customer goals, explains products, books advisor calls, collects documents, and sends application or payment updates.",
    businessName: "FinTrust Advisors",
    initials: "FT",
    accent: "Financial Services",
    icon: Banknote,
    stats: [
      { value: "95%", label: "Open rate", note: "Finance updates are seen" },
      { value: "3 sec", label: "First response", note: "Prospects get fast guidance" },
      { value: "24/7", label: "Lead coverage", note: "After-hours inquiries captured" },
      { value: "38%", label: "More applications", note: "Follow-ups keep cases moving" },
    ],
    chatMessages: [
      { from: "user", text: "Hi, I need a business loan" },
      { from: "bot", text: "Welcome to FinTrust. What loan amount are you looking for and what is your business turnover?" },
      { from: "user", text: "Rs. 20 lakh, turnover around Rs. 1.2 crore" },
      { from: "bot", text: "Thanks. You may qualify for working capital options. Please share city, business age, and preferred callback time." },
      { from: "user", text: "Pune, 4 years, tomorrow morning" },
      { from: "bot", text: "Advisor callback booked for tomorrow morning. I have also shared the document checklist." },
    ],
    servicesLabel: "Designed for finance teams",
    servicesTitle: "A WhatsApp lead desk for loans, investments, and advisory.",
    servicesBody: "Built for financial teams that need compliant intake, document collection, and clear handoff to advisors.",
    services: [
      { icon: ClipboardCheck, title: "Lead Qualification", body: "Captures income, turnover, loan amount, investment goal, risk profile, and timeline." },
      { icon: Banknote, title: "Product Guidance", body: "Explains loans, investments, wealth plans, and finance products in simple flows." },
      { icon: FileText, title: "Document Checklist", body: "Shares required documents and collects files directly inside WhatsApp." },
      { icon: CalendarCheck, title: "Advisor Booking", body: "Books callbacks with loan officers, advisors, or relationship managers." },
      { icon: BarChart3, title: "Application Updates", body: "Sends approval, pending document, disbursal, and portfolio update messages." },
      { icon: Bot, title: "RM Handoff", body: "Routes qualified customers to the right relationship manager with context." },
    ],
    imageOne: { src: "/images/finance_2.png", alt: "Financial service customer automation" },
    imageTwo: { src: "/images/finance_1.png", alt: "Financial service customer automation" },
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for lenders, advisors, wealth teams, and finance brokers.",
    audiences: [
      { icon: Banknote, title: "Loan Providers", text: "Eligibility checks, document collection, callbacks, and application updates." },
      { icon: BarChart3, title: "Wealth Advisors", text: "Goal discovery, risk profiling, meeting booking, and portfolio updates." },
      { icon: Users, title: "Finance Brokers", text: "Lead qualification, lender matching, document follow-up, and status messages." },
      { icon: ShieldCheck, title: "Compliance Teams", text: "KYC reminders, disclosure prompts, and audit-ready customer records." },
    ],
    journeyLabel: "Customer journey",
    journeyTitle: "From finance inquiry to application progress.",
    journey: [
      { step: "01", title: "Customer asks on WhatsApp", text: "The AI identifies the finance product and customer goal." },
      { step: "02", title: "Eligibility is checked", text: "Income, turnover, amount, tenure, risk profile, and timeline are captured." },
      { step: "03", title: "Documents and call are arranged", text: "Checklists, advisor slots, and next steps are shared." },
      { step: "04", title: "Status updates continue", text: "Pending documents, approval stages, and payment reminders are sent automatically." },
    ],
    dashboardTitle: "Financial Services Dashboard",
    resultsTitle: "Real results for financial service teams.",
    resultsBody: "Applications move faster when customer intake and follow-up are handled in one WhatsApp flow.",
    comparison: [
      ["Lead qualification", "Structured finance intake", "Incomplete form leads"],
      ["Document collection", "Checklist and upload in chat", "Files delayed over email"],
      ["Advisor calls", "Booked automatically", "Manual callbacks missed"],
      ["Application status", "Updates sent proactively", "Customers call for progress"],
      ["Conversion", "Follow-up keeps cases warm", "Prospects compare and disappear"],
    ],
    ctaTitle: "Ready to convert more finance leads?",
    ctaBody: "See a live WhatsApp financial-services flow for your products, documents, advisors, and application process.",
  },
  "it-services": {
    badge: "WhatsApp automation for IT services",
    title: "Qualify project leads and support tickets before your team steps in.",
    description:
      "DigitalBot captures project requirements, books discovery calls, collects technical details, triages support tickets, and routes work to the right team.",
    businessName: "TechOps IT Services",
    initials: "TO",
    accent: "IT Services",
    icon: Code2,
    stats: defaultStats,
    chatMessages: [
      { from: "user", text: "Hi, I need a website and CRM integration" },
      { from: "bot", text: "Welcome to TechOps. What type of website do you need and when do you want to launch?" },
      { from: "user", text: "B2B website, within 6 weeks" },
      { from: "bot", text: "Got it. Do you already use a CRM like Zoho, HubSpot, or Salesforce?" },
      { from: "user", text: "HubSpot" },
      { from: "bot", text: "Great. I have captured your requirements and booked a discovery call tomorrow at 2 PM." },
    ],
    servicesLabel: "Designed for IT teams",
    servicesTitle: "A WhatsApp intake and support desk for IT service companies.",
    servicesBody: "Built for agencies and managed service teams that need better project discovery and cleaner support handoffs.",
    services: [
      { icon: ClipboardCheck, title: "Requirement Intake", body: "Captures project type, goals, timeline, budget, stack, integrations, and stakeholders." },
      { icon: CalendarCheck, title: "Discovery Call Booking", body: "Books calls and sends requirement checklists before the meeting." },
      { icon: Code2, title: "Technical Triage", body: "Collects URLs, screenshots, errors, access needs, and priority before developer handoff." },
      { icon: Headphones, title: "Support Ticketing", body: "Creates structured support requests and keeps clients updated on progress." },
      { icon: Cloud, title: "Managed Service Updates", body: "Sends maintenance alerts, uptime messages, renewal reminders, and incident updates." },
      { icon: Bot, title: "Team Routing", body: "Routes cases to sales, support, development, or infrastructure teams with context." },
    ],
    imageOne: { src: "/images/it_service_1.png", alt: "IT services automation and support" },
    imageTwo: { src: "/images/it_service_2.png", alt: "SaaS team managing customer automation" },
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for web, software, MSP, and support teams.",
    audiences: [
      { icon: Code2, title: "Web and App Agencies", text: "Project intake, requirement forms, discovery calls, and proposal follow-up." },
      { icon: Cloud, title: "Managed IT Providers", text: "Ticket intake, incident alerts, maintenance updates, and renewals." },
      { icon: Headphones, title: "Support Teams", text: "Issue triage, screenshots, priority routing, and status updates." },
      { icon: Users, title: "Sales Teams", text: "Qualified project leads, call booking, budget capture, and CRM-ready handoff." },
    ],
    journeyLabel: "Project journey",
    journeyTitle: "From technical inquiry to assigned team.",
    journey: [
      { step: "01", title: "Client asks on WhatsApp", text: "The AI understands whether it is a project, support issue, or maintenance request." },
      { step: "02", title: "Technical details are captured", text: "Stack, timeline, error details, screenshots, priority, and budget are recorded." },
      { step: "03", title: "Call or ticket is created", text: "Discovery slots, ticket IDs, checklists, and next steps are shared." },
      { step: "04", title: "Updates continue", text: "Clients receive progress, approvals, deployment, and invoice reminders automatically." },
    ],
    dashboardTitle: "IT Services Dashboard",
    resultsTitle: "Real results for IT service teams.",
    resultsBody: "Projects and tickets move faster when intake is structured before the team gets involved.",
    comparison: [
      ["Requirement intake", "Structured project details", "Unclear calls and scattered notes"],
      ["Support tickets", "Screenshots and priority captured", "Agents chase basic details"],
      ["Team routing", "Right team assigned", "Requests land in the wrong inbox"],
      ["Client updates", "Automated progress messages", "Clients ask for status repeatedly"],
      ["Sales follow-up", "Proposal nudges in WhatsApp", "Warm project leads go quiet"],
    ],
    ctaTitle: "Ready to streamline IT inquiries?",
    ctaBody: "See a live WhatsApp IT-services flow for your projects, support tickets, teams, and client updates.",
  },
  recruitment: {
    badge: "WhatsApp automation for recruitment",
    title: "Screen candidates, book interviews, and keep hiring pipelines moving.",
    description:
      "DigitalBot answers job questions, screens applicants, collects resumes, schedules interviews, and sends status updates through WhatsApp.",
    businessName: "HireFlow Recruitment",
    initials: "HF",
    accent: "Recruitment",
    icon: UserCheck,
    stats: [
      { value: "95%", label: "Open rate", note: "Candidates see updates quickly" },
      { value: "3 sec", label: "First response", note: "Applicants get instant answers" },
      { value: "24/7", label: "Candidate support", note: "After-hours applications captured" },
      { value: "48%", label: "Faster screening", note: "Automation handles first filters" },
    ],
    chatMessages: [
      { from: "user", text: "Hi, I want to apply for sales executive role" },
      { from: "bot", text: "Welcome to HireFlow. How many years of sales experience do you have?" },
      { from: "user", text: "3 years" },
      { from: "bot", text: "Great. Please share your city, current CTC, expected CTC, notice period, and resume." },
      { from: "user", text: "Pune, 4 LPA, 5.5 LPA, 30 days" },
      { from: "bot", text: "Thanks. You match the first criteria. Interview slot available tomorrow at 11 AM or 4 PM." },
    ],
    servicesLabel: "Designed for hiring teams",
    servicesTitle: "A WhatsApp screening desk for recruiters and HR teams.",
    servicesBody: "Built for recruitment teams that need faster candidate screening, interview scheduling, and status communication.",
    services: [
      { icon: UserCheck, title: "Candidate Screening", body: "Captures experience, skills, location, CTC, notice period, and role interest." },
      { icon: FileText, title: "Resume Collection", body: "Collects resumes, portfolios, certificates, and ID documents directly in WhatsApp." },
      { icon: CalendarCheck, title: "Interview Scheduling", body: "Books interview slots and sends reminders to candidates and recruiters." },
      { icon: ClipboardCheck, title: "Job Matching", body: "Matches candidates to roles based on skills, location, experience, and availability." },
      { icon: MessageCircle, title: "Status Updates", body: "Sends shortlist, assignment, interview, offer, and rejection updates politely." },
      { icon: Bot, title: "Recruiter Handoff", body: "Routes qualified candidates to recruiters with full screening summary." },
    ],
    imageOne: { src: "/images/recruitment_1.png", alt: "Recruitment candidate screening automation" },
    imageTwo: { src: "/images/recruitment_2.png", alt: "Recruitment candidate screening automation" },
    audiencesLabel: "Who it helps",
    audiencesTitle: "One WhatsApp system for staffing agencies, HR teams, campuses, and recruiters.",
    audiences: [
      { icon: Users, title: "Staffing Agencies", text: "Bulk screening, resume collection, interview scheduling, and role matching." },
      { icon: BriefcaseBusiness, title: "Corporate HR", text: "Candidate intake, employee referrals, status updates, and interview reminders." },
      { icon: GraduationCap, title: "Campus Hiring", text: "Student registration, eligibility checks, drive reminders, and result updates." },
      { icon: UserCheck, title: "Recruiters", text: "Qualified candidate summaries, follow-up nudges, and pipeline visibility." },
    ],
    journeyLabel: "Candidate journey",
    journeyTitle: "From application to scheduled interview.",
    journey: [
      { step: "01", title: "Candidate applies on WhatsApp", text: "The AI identifies the role and asks screening questions." },
      { step: "02", title: "Profile is captured", text: "Experience, skills, location, CTC, notice period, and resume are saved." },
      { step: "03", title: "Interview gets scheduled", text: "Eligible candidates choose slots and receive reminders automatically." },
      { step: "04", title: "Status updates continue", text: "Shortlist, assignment, interview, and offer updates are sent on time." },
    ],
    dashboardTitle: "Recruitment Pipeline Dashboard",
    resultsTitle: "Real results for recruitment teams.",
    resultsBody: "Hiring pipelines move faster when screening and scheduling happen instantly on WhatsApp.",
    comparison: [
      ["Screening", "Structured candidate filters", "Recruiters manually call everyone"],
      ["Resume collection", "Files uploaded in WhatsApp", "Resumes scattered in email"],
      ["Interview scheduling", "Slots confirmed automatically", "Back-and-forth coordination"],
      ["Candidate experience", "Timely status updates", "Applicants stay confused"],
      ["Recruiter focus", "Qualified candidates reach staff", "Teams spend time on low-fit profiles"],
    ],
    ctaTitle: "Ready to speed up recruitment?",
    ctaBody: "See a live WhatsApp recruitment flow for your roles, screening questions, interview slots, and hiring team.",
  },
}
