import type { IndustryVoiceAgentConfig } from "./industry-voice-agent-page"

export const insuranceVoiceAgentConfig: IndustryVoiceAgentConfig = {
  badge: "Insurance Voice Agent",
  heroTitle: "Turn insurance calls into",
  heroAccent: "qualified policy conversations.",
  heroDescription:
    "AI answers policy inquiries, qualifies prospects, captures coverage needs, and helps your team follow up with the right context.",
  heroImage: "/images/voice_insurance_1.png",
  heroImageAlt: "Insurance voice agent helping policy teams handle customer calls",
  heroFrameClassName: "!min-h-[320px] sm:!min-h-[430px] lg:!min-h-[560px]",
  heroVisualClassName: "!min-h-[320px] bg-transparent sm:!min-h-[430px] lg:!min-h-[560px]",
  heroImageClassName:
    "!max-w-[520px] translate-x-4 opacity-95 mix-blend-multiply [mask-image:radial-gradient(ellipse_at_center,#000_58%,rgba(0,0,0,0.72)_76%,transparent_100%)] [-webkit-mask-image:radial-gradient(ellipse_at_center,#000_58%,rgba(0,0,0,0.72)_76%,transparent_100%)] lg:translate-x-10",
  trustedTitle: "Built for agencies, brokers, and insurance support teams",
  trustedSegments: ["Insurance Agencies", "Brokers", "Claims Teams", "Policy Renewals", "Health Cover", "Motor Insurance", "Life Insurance", "CRM Pipelines"],
  stats: [
    { value: "24/7", label: "policy calls" },
    { value: "3 sec", label: "first reply" },
    { value: "40%", label: "faster follow-up" },
  ],
  intelligenceEyebrow: "Policy intelligence",
  intelligenceTitle: "Know which insurance callers need urgent follow-up.",
  intelligenceBody:
    "The agent captures the customer's coverage type, renewal stage, claim reason, and buying urgency before your advisor steps in.",
  intelligenceBullets: [
    "Answers approved questions about policies, documents, premiums, renewals, and claims process.",
    "Separates new policy buyers, renewal customers, and claim support requests automatically.",
    "Creates a clean summary for advisors with coverage need, urgency, and next step.",
  ],
  intelligenceImage: "/images/voice_insurance_2.png",
  intelligenceImageAlt: "Insurance team reviewing qualified voice leads",
  intelligenceImageClassName: "-translate-x-4 lg:-translate-x-8",
  highlights: [
    { title: "Coverage need", text: "Captures policy type, sum insured, family size, vehicle type, or business risk." },
    { title: "Renewal readiness", text: "Identifies renewal dates, payment intent, and pending document needs." },
    { title: "Advisor handoff", text: "Sends a structured summary so advisors can call with context." },
  ],
  featuresTitle: "One voice agent for every insurance inquiry.",
  features: [
    { title: "Answers policy calls", text: "Handles plan, premium, document, claim, and renewal questions instantly." },
    { title: "Qualifies prospects", text: "Captures policy interest, budget, coverage need, and decision timeline." },
    { title: "Schedules callbacks", text: "Books advisor callbacks for high-intent prospects and renewal customers." },
    { title: "Handles claims intake", text: "Collects claim category, policy details, incident date, and urgency." },
    { title: "Sends summaries", text: "Gives your team caller details, policy need, and recommended next action." },
    { title: "Follows up renewals", text: "Re-engages customers before expiry and nudges pending payments." },
  ],
  integrationsTitle: "Connect calls, renewals, claims, and advisor handoffs.",
  integrationsBody:
    "Use the agent with your call process, CRM, policy records, WhatsApp reminders, and appointment workflows.",
  integrationsBadge: "One voice layer for every insurance customer",
  integrationsImage: "/images/voice_insurance_3.png",
  integrationsImageAlt: "Insurance workflow connected with AI voice calls",
  integrationsImageClassName: "translate-x-4 lg:translate-x-8",
  integrations: [
    { title: "Phone calls", text: "Capture inbound calls, missed calls, and campaign responses." },
    { title: "WhatsApp reminders", text: "Send renewal reminders, document lists, and advisor callbacks." },
    { title: "Calendar slots", text: "Collect callback times for advisors and claims teams." },
    { title: "CRM updates", text: "Push policy type, customer stage, urgency, and follow-up owner." },
    { title: "Policy knowledge", text: "Answer approved product and process questions." },
    { title: "Rules and handoff", text: "Escalate claims, complaints, or hot policy buyers instantly." },
  ],
  processTitle: "From insurance inquiry to advisor handoff in one flow.",
  processBody: "A simple workflow focused on qualifying callers, collecting policy context, and routing the right next step.",
  processImage: "/images/voice_insurance_4.png",
  processImageAlt: "Insurance AI voice agent workflow",
  processSteps: [
    { num: 1, title: "Call comes in", text: "Customer asks about a policy, renewal, or claim." },
    { num: 2, title: "AI qualifies", text: "Coverage type, urgency, documents, and callback preference are captured." },
    { num: 3, title: "Next step set", text: "The agent schedules a callback or shares approved information." },
    { num: 4, title: "Team gets summary", text: "Advisor receives context before calling the customer." },
  ],
}

export const healthcareVoiceAgentConfig: IndustryVoiceAgentConfig = {
  badge: "Healthcare Voice Agent",
  heroTitle: "Turn patient calls into",
  heroAccent: "confirmed appointments.",
  heroDescription:
    "AI answers clinic calls, collects patient details, books appointments, sends reminders, and routes urgent cases to your staff.",
  heroImage: "/images/voice_healthcare_1.png",
  heroImageAlt: "Healthcare voice agent managing patient appointment calls",
  heroImageClassName: "translate-x-4 lg:translate-x-10",
  trustedTitle: "Built for clinics, hospitals, labs, and wellness centers",
  trustedSegments: ["Clinics", "Hospitals", "Diagnostics", "Dental Care", "Wellness Centers", "Specialists", "Reception Teams", "Patient Support"],
  stats: [
    { value: "24/7", label: "patient calls" },
    { value: "3 sec", label: "first reply" },
    { value: "60%", label: "less no-show" },
  ],
  intelligenceEyebrow: "Patient intake",
  intelligenceTitle: "Capture patient needs before your front desk responds.",
  intelligenceBody:
    "The agent collects reason for visit, preferred doctor, timing, location, and urgency while keeping the conversation simple for patients.",
  intelligenceBullets: [
    "Answers approved questions about doctors, timings, location, fees, and reports.",
    "Books appointments and captures patient details without manual back-and-forth.",
    "Routes urgent or sensitive cases to staff with full call context.",
  ],
  intelligenceImage: "/images/voice_healthcare_2.png",
  intelligenceImageAlt: "Healthcare staff using AI voice appointment summaries",
  highlights: [
    { title: "Patient details", text: "Name, phone, reason for visit, doctor preference, and visit timing." },
    { title: "Appointment readiness", text: "Captures preferred slot and sends confirmation workflows." },
    { title: "Front desk handoff", text: "Shares structured call notes with your reception team." },
  ],
  featuresTitle: "One voice agent for your patient calls.",
  features: [
    { title: "Answers clinic calls", text: "Handles timings, fees, doctor availability, location, and basic service questions." },
    { title: "Books appointments", text: "Collects preferred date, time, doctor, and patient information." },
    { title: "Sends reminders", text: "Reduces no-shows with appointment confirmation and reminder flows." },
    { title: "Handles reports queries", text: "Guides patients on report status, collection process, and next steps." },
    { title: "Escalates urgent calls", text: "Transfers critical or sensitive cases to human staff quickly." },
    { title: "Follows up patients", text: "Runs post-visit follow-ups and feedback collection." },
  ],
  integrationsTitle: "Connect calls, appointments, reminders, and patient handoffs.",
  integrationsBody:
    "Use the agent with your calendar, front desk process, WhatsApp updates, patient database, and support workflow.",
  integrationsBadge: "One voice layer for every patient inquiry",
  integrationsImage: "/images/voice_healthcare_3.png",
  integrationsImageAlt: "Healthcare voice agent integrations",
  integrations: [
    { title: "Phone calls", text: "Answer inbound calls and missed patient calls." },
    { title: "WhatsApp confirmations", text: "Send appointment details, reminders, and follow-up messages." },
    { title: "Calendar slots", text: "Collect preferred appointment dates and timings." },
    { title: "Patient records", text: "Push patient details, visit reason, and appointment status." },
    { title: "Doctor availability", text: "Answer approved schedule and specialty questions." },
    { title: "Escalation rules", text: "Route urgent, emergency, or complex cases to staff." },
  ],
  processTitle: "From patient inquiry to booked appointment.",
  processBody: "A healthcare workflow focused on quick response, clean intake, and reliable appointment handling.",
  processImage: "/images/voice_healthcare_4.png",
  processImageAlt: "Patient appointment workflow with voice AI",
  processSteps: [
    { num: 1, title: "Patient calls", text: "Patient asks for a doctor, appointment, report, or clinic information." },
    { num: 2, title: "AI collects details", text: "Reason for visit, preferred slot, doctor, and contact details are captured." },
    { num: 3, title: "Booking flow starts", text: "Appointment request or confirmation moves into your calendar workflow." },
    { num: 4, title: "Team gets summary", text: "Reception receives a clear patient summary and next step." },
  ],
}

export const restaurantsVoiceAgentConfig: IndustryVoiceAgentConfig = {
  badge: "Restaurant Voice Agent",
  heroTitle: "Turn restaurant calls into",
  heroAccent: "reservations and orders.",
  heroDescription:
    "AI answers restaurant calls, handles table booking requests, captures order inquiries, shares timings, and helps staff avoid missed calls during busy hours.",
  heroImage: "/images/voice_resturant_1.png",
  heroImageAlt: "Restaurant voice agent handling reservation calls",
  trustedTitle: "Built for restaurants, cafes, cloud kitchens, and hospitality teams",
  trustedSegments: ["Restaurants", "Cafes", "Cloud Kitchens", "Fine Dining", "QSR Teams", "Catering", "Reservations", "Delivery Support"],
  stats: [
    { value: "24/7", label: "call cover" },
    { value: "3 sec", label: "first reply" },
    { value: "50%", label: "fewer missed calls" },
  ],
  intelligenceEyebrow: "Reservation intelligence",
  intelligenceTitle: "Capture guest intent even when the floor is busy.",
  intelligenceBody:
    "The agent collects party size, preferred time, occasion, order details, and callback needs so your team can respond without losing guests.",
  intelligenceBullets: [
    "Answers approved questions about timings, location, menu, availability, and offers.",
    "Collects reservation details, dietary preferences, and special requests.",
    "Routes large party, catering, or complaint calls to the right staff member.",
  ],
  intelligenceImage: "/images/voice_resturant_2.png",
  intelligenceImageAlt: "Restaurant team managing reservations with voice AI",
  highlights: [
    { title: "Guest details", text: "Name, phone, party size, preferred time, and occasion." },
    { title: "Order intent", text: "Captures delivery, takeaway, catering, or menu inquiry needs." },
    { title: "Staff handoff", text: "Sends clean summaries for reservations and urgent callbacks." },
  ],
  featuresTitle: "One voice agent for restaurant calls.",
  features: [
    { title: "Answers busy-hour calls", text: "Responds when staff are handling dine-in guests or kitchen rush." },
    { title: "Takes reservations", text: "Collects party size, date, time, and special requests." },
    { title: "Handles menu questions", text: "Answers approved questions about cuisines, timings, offers, and location." },
    { title: "Captures order inquiries", text: "Collects takeaway, delivery, and catering call details." },
    { title: "Escalates complaints", text: "Routes guest issues to managers with call context." },
    { title: "Sends confirmations", text: "Triggers WhatsApp or SMS confirmation flows for bookings." },
  ],
  integrationsTitle: "Connect calls, reservations, orders, and guest updates.",
  integrationsBody:
    "Use the agent with your phone line, booking sheet, WhatsApp updates, order desk, and manager escalation process.",
  integrationsBadge: "One voice layer for every guest call",
  integrationsImage: "/images/voice_resturant_3.png",
  integrationsImageAlt: "Restaurant reservation voice workflow",
  integrations: [
    { title: "Phone calls", text: "Capture inbound and missed restaurant calls." },
    { title: "WhatsApp updates", text: "Send booking confirmations and location details." },
    { title: "Reservation slots", text: "Collect date, time, party size, and preferences." },
    { title: "Guest records", text: "Push guest name, phone, request type, and urgency." },
    { title: "Menu knowledge", text: "Answer approved menu, cuisine, timing, and offer questions." },
    { title: "Manager handoff", text: "Escalate complaints, large bookings, and catering requests." },
  ],
  processTitle: "From guest call to reservation handoff.",
  processBody: "A restaurant workflow focused on answering every call and keeping reservation details clean.",
  processImage: "/images/voice_resturant_4.png",
  processImageAlt: "Restaurant reservation workflow with voice AI",
  processSteps: [
    { num: 1, title: "Guest calls", text: "Caller asks about reservation, menu, location, or order details." },
    { num: 2, title: "AI captures request", text: "Party size, timing, phone number, and special instructions are collected." },
    { num: 3, title: "Next step set", text: "Confirmation, callback, or manager handoff is triggered." },
    { num: 4, title: "Team gets summary", text: "Staff receive the guest request with all important details." },
  ],
}

export const financeVoiceAgentConfig: IndustryVoiceAgentConfig = {
  badge: "Finance Voice Agent",
  heroTitle: "Turn finance calls into",
  heroAccent: "qualified applications.",
  heroDescription:
    "AI answers finance inquiries, qualifies loan or investment leads, captures eligibility details, and routes high-intent customers to your team.",
  heroImage: "/images/voice_finance_1.png",
  heroImageAlt: "Finance voice agent qualifying customer calls",
  trustedTitle: "Built for lenders, advisors, NBFCs, and finance teams",
  trustedSegments: ["Loan Teams", "NBFCs", "Advisors", "Wealth Teams", "Credit Teams", "Fintech", "Collections", "CRM Pipelines"],
  stats: [
    { value: "24/7", label: "lead cover" },
    { value: "3 sec", label: "first reply" },
    { value: "45%", label: "faster qualification" },
  ],
  intelligenceEyebrow: "Finance qualification",
  intelligenceTitle: "Know which finance callers are ready to apply.",
  intelligenceBody:
    "The agent captures product interest, income range, loan amount, timeline, location, and documents before your sales team follows up.",
  intelligenceBullets: [
    "Answers approved questions about loans, eligibility, rates, documents, and process.",
    "Separates casual inquiries from ready-to-apply finance leads.",
    "Creates a clean call summary with eligibility signals and recommended next action.",
  ],
  intelligenceImage: "/images/voice_finance_2.png",
  intelligenceImageAlt: "Finance team reviewing qualified AI voice leads",
  highlights: [
    { title: "Eligibility details", text: "Income, employment type, loan amount, city, and timeline." },
    { title: "Product intent", text: "Identifies loan, card, investment, insurance, or advisory interest." },
    { title: "Sales handoff", text: "Routes high-intent customers with structured context." },
  ],
  featuresTitle: "One voice agent for finance inquiries.",
  features: [
    { title: "Answers finance calls", text: "Handles approved questions about eligibility, documents, rates, and timelines." },
    { title: "Qualifies applicants", text: "Captures income, requirement, credit context, and product need." },
    { title: "Books advisor calls", text: "Schedules callbacks with loan officers or finance advisors." },
    { title: "Handles document queries", text: "Guides customers on required documents and next steps." },
    { title: "Sends lead summaries", text: "Gives your team product interest, eligibility details, and urgency." },
    { title: "Follows up warm leads", text: "Nudges pending applications and incomplete document submissions." },
  ],
  integrationsTitle: "Connect calls, applications, documents, and sales handoffs.",
  integrationsBody:
    "Use the agent with CRM, call campaigns, WhatsApp updates, eligibility workflows, and advisor scheduling.",
  integrationsBadge: "One voice layer for every finance inquiry",
  integrationsImage: "/images/voice_finance_3.png",
  integrationsImageAlt: "Finance voice agent integrations",
  integrations: [
    { title: "Phone calls", text: "Capture inbound calls and campaign responses." },
    { title: "WhatsApp updates", text: "Send document lists, callback confirmations, and status nudges." },
    { title: "Advisor slots", text: "Collect preferred callback times for finance advisors." },
    { title: "CRM updates", text: "Push product, income, amount, and application stage." },
    { title: "Product knowledge", text: "Answer approved eligibility, document, and process questions." },
    { title: "Rules and handoff", text: "Escalate high-value or urgent leads instantly." },
  ],
  processTitle: "From finance inquiry to qualified application.",
  processBody: "A qualification workflow focused on faster intake, cleaner data, and better advisor callbacks.",
  processImage: "/images/voice_finance_4.png",
  processImageAlt: "Finance AI voice workflow",
  processSteps: [
    { num: 1, title: "Customer calls", text: "Caller asks about a loan, card, investment, or financial service." },
    { num: 2, title: "AI qualifies", text: "Need, amount, income, documents, and timeline are captured." },
    { num: 3, title: "Callback booked", text: "Advisor call or application next step is scheduled." },
    { num: 4, title: "Team gets summary", text: "Sales team receives eligibility context before calling." },
  ],
}

export const educationVoiceAgentConfig: IndustryVoiceAgentConfig = {
  badge: "Education Voice Agent",
  heroTitle: "Turn education calls into",
  heroAccent: "qualified admissions leads.",
  heroDescription:
    "AI answers course inquiries, qualifies students, captures program interest, and helps counselors follow up before leads go cold.",
  heroImage: "/images/voice_education_1.png",
  heroImageAlt: "Education voice agent answering student admission calls",
  trustedTitle: "Built for schools, colleges, coaching centers, and edtech teams",
  trustedSegments: ["Schools", "Colleges", "Coaching Centers", "EdTech", "Admissions", "Counselors", "MBA Programs", "Campus Teams"],
  stats: [
    { value: "24/7", label: "lead cover" },
    { value: "3 sec", label: "first reply" },
    { value: "2x", label: "faster counseling" },
  ],
  intelligenceEyebrow: "Admissions intelligence",
  intelligenceTitle: "Capture student intent before your counselor calls.",
  intelligenceBody:
    "The agent collects course interest, qualification, location, budget, admission timeline, and counseling preference.",
  intelligenceBullets: [
    "Answers approved questions about courses, fees, eligibility, batches, and admissions.",
    "Separates serious students from casual inquiries using program fit and timeline.",
    "Creates counselor-ready lead summaries with student context and next step.",
  ],
  intelligenceImage: "/images/voice_education_2.png",
  intelligenceImageAlt: "Education admissions team reviewing voice lead summaries",
  intelligenceImageFrameClassName: "overflow-visible",
  intelligenceImageClassName:
    "!w-[118%] !max-w-none [mask-image:none] [-webkit-mask-image:none] lg:[mask-image:none]",
  highlights: [
    { title: "Student profile", text: "Name, qualification, course interest, location, and timeline." },
    { title: "Counseling readiness", text: "Captures preferred callback time and admission urgency." },
    { title: "Counselor handoff", text: "Routes hot leads with course fit and conversation context." },
  ],
  featuresTitle: "One voice agent for education inquiries.",
  features: [
    { title: "Answers course calls", text: "Handles fees, eligibility, batch timing, location, and admission questions." },
    { title: "Qualifies students", text: "Captures qualification, course interest, budget, and admission timeline." },
    { title: "Books counseling calls", text: "Schedules student or parent callbacks with counselors." },
    { title: "Handles campus queries", text: "Guides callers on campus, documents, forms, and process." },
    { title: "Sends lead summaries", text: "Gives counselors student profile, course interest, and urgency." },
    { title: "Follows up inquiries", text: "Re-engages old leads and incomplete application forms." },
  ],
  integrationsTitle: "Connect calls, counselors, forms, and admission workflows.",
  integrationsBody:
    "Use the agent with your CRM, counselor assignments, WhatsApp updates, form workflows, and campaign calls.",
  integrationsBadge: "One voice layer for every admissions inquiry",
  integrationsImage: "/images/voice_education_3.png",
  integrationsImageAlt: "Education voice agent integrations",
  integrationsImageFrameClassName: "overflow-visible",
  integrationsImageClassName:
    "!w-[118%] !max-w-none [mask-image:none] [-webkit-mask-image:none] lg:[mask-image:none]",
  integrations: [
    { title: "Phone calls", text: "Capture inbound admission calls and campaign responses." },
    { title: "WhatsApp updates", text: "Send brochure links, form reminders, and counseling confirmations." },
    { title: "Counselor slots", text: "Collect preferred callback times for counselors." },
    { title: "CRM updates", text: "Push course interest, student profile, and lead stage." },
    { title: "Course knowledge", text: "Answer approved fees, eligibility, and batch questions." },
    { title: "Rules and handoff", text: "Route hot leads by course, campus, or counselor availability." },
  ],
  processTitle: "From student inquiry to counselor handoff.",
  processBody: "An admissions workflow focused on instant response, clean qualification, and faster counseling.",
  processImage: "/images/voice_education_4.png",
  processImageAlt: "Education AI voice workflow",
  processImageClassName: "!max-w-[560px]",
  processSteps: [
    { num: 1, title: "Student calls", text: "Caller asks about a course, fees, batch, or admission process." },
    { num: 2, title: "AI qualifies", text: "Course interest, qualification, timeline, and contact details are captured." },
    { num: 3, title: "Counseling set", text: "Callback or counseling session is requested with preferred timing." },
    { num: 4, title: "Team gets summary", text: "Counselor receives student context before follow-up." },
  ],
}

export const ecommerceVoiceAgentConfig: IndustryVoiceAgentConfig = {
  badge: "E-commerce Voice Agent",
  heroTitle: "Turn e-commerce calls into",
  heroAccent: "orders and resolved support.",
  heroDescription:
    "AI answers order calls, handles product questions, captures support issues, and helps your team reduce missed sales and repetitive tickets.",
  heroImage: "/images/voice_ecommerce_1.png",
  heroImageAlt: "E-commerce voice agent handling product and order calls",
  trustedTitle: "Built for D2C brands, online stores, marketplaces, and support teams",
  trustedSegments: ["D2C Brands", "Online Stores", "Marketplaces", "Shopify Teams", "Support Teams", "COD Orders", "Returns", "Delivery Updates"],
  stats: [
    { value: "24/7", label: "support cover" },
    { value: "3 sec", label: "first reply" },
    { value: "35%", label: "fewer tickets" },
  ],
  intelligenceEyebrow: "Order intelligence",
  intelligenceTitle: "Know which shoppers need sales help or support.",
  intelligenceBody:
    "The agent captures order ID, product interest, issue type, delivery concern, return request, and buying intent.",
  intelligenceBullets: [
    "Answers approved questions about products, delivery, returns, exchange, payment, and order status.",
    "Separates sales calls, order support, return requests, and complaints automatically.",
    "Creates clean summaries so support or sales teams can act faster.",
  ],
  intelligenceImage: "/images/voice_ecommerce_2.png",
  intelligenceImageAlt: "E-commerce support team reviewing AI voice summaries",
  highlights: [
    { title: "Order context", text: "Order ID, product, delivery status, issue type, and contact details." },
    { title: "Buyer intent", text: "Captures product interest, quantity, budget, and purchase urgency." },
    { title: "Support handoff", text: "Routes returns, complaints, and high-value sales calls with context." },
  ],
  featuresTitle: "One voice agent for e-commerce calls.",
  features: [
    { title: "Answers order calls", text: "Handles delivery, return, exchange, payment, and order status questions." },
    { title: "Qualifies shoppers", text: "Captures product interest, use case, quantity, and buying timeline." },
    { title: "Handles COD confirmation", text: "Confirms cash-on-delivery orders and delivery preferences." },
    { title: "Captures support issues", text: "Collects issue type, order ID, photos needed, and urgency." },
    { title: "Sends summaries", text: "Gives your team call reason, customer details, and next action." },
    { title: "Follows up carts", text: "Re-engages abandoned carts and pending payment customers." },
  ],
  integrationsTitle: "Connect calls, orders, support, and customer updates.",
  integrationsBody:
    "Use the agent with your store, CRM, helpdesk, WhatsApp updates, COD confirmation, and support workflows.",
  integrationsBadge: "One voice layer for every shopper call",
  integrationsImage: "/images/voice_ecommerce_3.png",
  integrationsImageAlt: "E-commerce voice agent integrations",
  integrations: [
    { title: "Phone calls", text: "Capture inbound support calls and sales inquiries." },
    { title: "WhatsApp updates", text: "Send order links, support instructions, and delivery updates." },
    { title: "Callback slots", text: "Collect preferred time for sales or support callbacks." },
    { title: "CRM updates", text: "Push order ID, issue type, product interest, and stage." },
    { title: "Product knowledge", text: "Answer approved product, delivery, and return questions." },
    { title: "Rules and handoff", text: "Escalate VIP customers, complaints, or high-value sales calls." },
  ],
  processTitle: "From shopper call to order or support handoff.",
  processBody: "An e-commerce workflow focused on faster answers, cleaner support intake, and more recovered sales.",
  processImage: "/images/voice_ecommerce_4.png",
  processImageAlt: "E-commerce AI voice workflow",
  processSteps: [
    { num: 1, title: "Customer calls", text: "Caller asks about a product, order, delivery, return, or payment." },
    { num: 2, title: "AI identifies intent", text: "Order details, issue type, product interest, and urgency are captured." },
    { num: 3, title: "Next step triggered", text: "Support handoff, COD confirmation, callback, or product guidance happens." },
    { num: 4, title: "Team gets summary", text: "Sales or support receives the full call context." },
  ],
}

export const collectionsVoiceAgentConfig: IndustryVoiceAgentConfig = {
  badge: "Collections Voice Agent",
  heroTitle: "Turn collection calls into",
  heroAccent: "structured payment follow-ups.",
  heroDescription:
    "AI handles payment reminder calls, captures borrower responses, records promises to pay, and routes urgent or sensitive cases to your collections team.",
  heroImage: "/images/voice_collection_1.png",
  heroImageAlt: "Collections voice agent handling payment reminder calls",
  heroImageClassName: "!max-w-[1080px]",
  trustedTitle: "Built for finance, lending, subscription, and receivables teams",
  trustedSegments: ["Collections Teams", "NBFCs", "Loan Providers", "Subscription Billing", "Receivables", "Payment Follow-up", "Renewals", "CRM Pipelines"],
  stats: [
    { value: "24/7", label: "follow-up cover" },
    { value: "3 sec", label: "first reply" },
    { value: "40%", label: "less manual chase" },
  ],
  intelligenceEyebrow: "Payment follow-up",
  intelligenceTitle: "Know who is ready to pay, who needs help, and who needs escalation.",
  intelligenceBody:
    "The agent captures payment intent, reason for delay, preferred payment date, dispute details, and callback needs in a consistent format.",
  intelligenceBullets: [
    "Runs polite reminder calls for overdue invoices, EMIs, renewals, and subscriptions.",
    "Captures promise-to-pay dates, partial payment intent, and payment blockers.",
    "Escalates disputes, complaints, and sensitive cases to a human team member.",
  ],
  intelligenceImage: "/images/voice_collection_2.png",
  intelligenceImageAlt: "Collections team reviewing payment follow-up summaries",
  intelligenceImageFrameClassName: "overflow-visible",
  intelligenceImageClassName: "!w-[112%] !max-w-none",
  highlights: [
    { title: "Payment intent", text: "Captures promise-to-pay date, amount, and preferred payment method." },
    { title: "Delay reason", text: "Records disputes, cash-flow issues, wrong contact, or support needs." },
    { title: "Team handoff", text: "Routes urgent or sensitive cases with full call context." },
  ],
  featuresTitle: "One voice agent for collections follow-up.",
  features: [
    { title: "Runs reminder calls", text: "Handles polite payment reminders for invoices, EMIs, renewals, and dues." },
    { title: "Captures promises", text: "Records payment date, partial amount, and customer commitment." },
    { title: "Handles objections", text: "Collects delay reasons, disputes, and support requirements." },
    { title: "Sends payment nudges", text: "Triggers WhatsApp or SMS payment links and reminder messages." },
    { title: "Updates CRM", text: "Adds call outcome, payment intent, and next follow-up stage." },
    { title: "Escalates exceptions", text: "Transfers disputes, complaints, and high-value accounts to humans." },
  ],
  integrationsTitle: "Connect calls, payment links, CRM outcomes, and escalation rules.",
  integrationsBody:
    "Use the agent with your billing system, CRM, WhatsApp payment reminders, dialer workflows, and collections dashboards.",
  integrationsBadge: "One voice layer for every payment follow-up",
  integrationsImage: "/images/voice_collection_3.png",
  integrationsImageAlt: "Collections voice agent integrations",
  integrations: [
    { title: "Phone calls", text: "Run inbound and outbound payment reminder calls." },
    { title: "WhatsApp nudges", text: "Send payment links, receipts, and reminder messages." },
    { title: "Follow-up slots", text: "Capture preferred callback time and payment date." },
    { title: "CRM updates", text: "Push outcome, promise-to-pay, dispute status, and next action." },
    { title: "Billing context", text: "Use approved invoice, EMI, renewal, or subscription details." },
    { title: "Escalation rules", text: "Route disputes, complaints, and sensitive calls to your team." },
  ],
  processTitle: "From payment reminder to clean collections outcome.",
  processBody: "A collections workflow focused on polite reminders, structured outcomes, and faster human escalation when needed.",
  processImage: "/images/voice_collection_4.png",
  processImageAlt: "Collections AI voice workflow",
  processSteps: [
    { num: 1, title: "Call is placed", text: "Customer receives a reminder for EMI, invoice, renewal, or pending payment." },
    { num: 2, title: "AI captures response", text: "Payment intent, reason for delay, and preferred payment date are recorded." },
    { num: 3, title: "Next action set", text: "Payment link, reminder, callback, or escalation is triggered." },
    { num: 4, title: "Team gets summary", text: "Collections team receives outcome and follow-up context." },
  ],
}
